/**
 * @file ai_host_events.h
 * @brief Events generated by the AI Host interface for application consumption.
 */

#ifndef INC_AI_HOST_AI_HOST_EVENTS_H_
#define INC_AI_HOST_AI_HOST_EVENTS_H_

#include <stdint.h>

/**
 * @brief Types of events the AI Host service can broadcast.
 */
typedef enum {
    AI_EVENT_CONNECTED = 0,
    AI_EVENT_DISCONNECTED,
    AI_EVENT_WAKE_WORD_DETECTED,
    AI_EVENT_START_LISTENING,
    AI_EVENT_STOP_LISTENING,
    AI_EVENT_PROCESSING,
    AI_EVENT_SPEAKING_START,
    AI_EVENT_SPEAKING_STOP
} ai_host_event_type_t;

typedef struct {
    ai_host_event_type_t type;
    uint32_t timestamp_ms;
    void* event_data;
} ai_host_event_t;

/**
 * @brief Callback signature for AI Host event subscribers.
 */
typedef void (*ai_host_event_cb_t)(const ai_host_event_t *event, void *user_ctx);

#endif /* INC_AI_HOST_AI_HOST_EVENTS_H_ */
